### ISSUE TITLE
Alternative results reporting

### ISSUE THREAD

**Issue by hugo-tubi** [willdeuschle/ry#1]
Interesting project!

Instead of print simple matched values, I'm thinking would it be useful when keeping the main tree. For example.

On yaml file:
```
a:
  b1:
    c:
      c: crabs_1
    d: bears
  b2:
    c: crabs_2
    d: bears
  b3:
    e:
      - f:
          c: crabs_3
          g: bears
      - f:
          g:
            c: crabs_4
            h: bears
      - f: bears
```

Result of `ry test_splat.yml 'a.**.c' -m tree`:
```
a:
  b1:
    c:
      c: crabs_1
  b2:
    c: crabs_2
  b3:
    e:
      - f:
          c: crabs_3
      - f:
          g:
            c: crabs_4
```
